#配置dev环境
spring:
  profiles: dev
  application:
    name: ylfoodmsc-eurekaServer-config

server:
  port: 8001

eureka:
  client:
    #暴露服务中心地址
    service-url:
      defaultZone: http://localhost:8001/eureka
     #指定是否向注册中心注册自己
    register-with-eureka: false
    #指定此客户端是否能够获取eureka注册信息
    fetch-registry: false
  instance:
    hostname: localhost

---
#配置test环境
spring:
  profiles: test
  application:
    name: ylfoodmsc-eurekaServer-config

server:
  port: 8002

eureka:
  client:
    #暴露服务中心地址
    service-url:
      defaultZone: http://localhost:8002/eureka
     #指定是否向注册中心注册自己
    register-with-eureka: false
    #指定此客户端是否能够获取eureka注册信息
    fetch-registry: false
  instance:
    hostname: localhost